Updated license and links
twitterdev/cannonball-web pull request #12
Opened 2017-04-20 21:18 UTC by mikebonnell

2017-05-01 02:25 UTC, alexsinger requested changes

2017-05-01 02:25 UTC, alexsinger commented on views/error.ejs
> +    <p>© 2015 Twitter &middot; Demo by <a href="https://twitter.com/romainhuet">Romain Huet</a> &middot; <a href="https://github.com/crashlytics/cannonball-web">Code on GitHub</a></p>
`2015 Twitter` needs to be changed

2017-05-01 02:25 UTC, alexsinger commented on views/index.ejs
> +    <p>© 2015 Twitter &middot; Demo by <a href="https://twitter.com/romainhuet">Romain Huet</a> &middot; <a href="https://github.com/crashlytics/cannonball-web">Code on GitHub</a></p>
`2015 Twitter` needs to be changed

2017-06-02 13:50 UTC, kb approved these changes

2017-06-02 13:53 UTC, alexsinger approved these changes

2017-06-02 13:53 UTC, merged